spring:
  profiles: 
    active:
    - dev
---
spring:
  profiles: dev     
  application:
    name: springcloud-study-config-gxs-dev
---
spring:
  profiles: test    
  application:
      name: springcloud-study-config-gxs-test